version: '3'

networks:
  mired:
    driver: bridge  # Asegúrate de usar un controlador como 'bridge' para Docker
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  nginx:
    image: pablorodseg/nginx_proyectofinaldiu:2
    ports:
      - "80:80"
    depends_on:
      - app-tutorials
      - app-agenda
    networks:
      mired:
        ipv4_address: 182.28.0.14

  db:
    image: bitnami/mongodb:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      mired:
        ipv4_address: 182.28.0.11

  app-tutorials:
    image: pablorodseg/tutorials2025:2
    container_name: tutorialsapp
    ports:
      - "8098:8098"
    depends_on:
      - db
    networks:
      mired:
        ipv4_address: 182.28.0.12

  app-agenda:
    image: pablorodseg/agenda2025:2
    container_name: agendaapp
    ports:
      - "8099:8099"
    depends_on:
      - db
   networks:
      mired:
        ipv4_address: 182.28.0.13
